### ISSUE TITLE
932 maps to windows-31j, not shift_jis

### ISSUE THREAD

**Issue by trejkaz** [ConradIrwin/encoding-codepage#2]
Microsoft code page 932 (MS932) is an alias for the code page windows-31j, not Shift-JIS (in the same sense that MS1252 is windows-1252 and not ISO-8859-1.)

Although, the mis-mapping of 932 to Shift_JIS is a _very_ common misunderstanding.

I haven't checked any of the other mappings but I would question 936 and 949 as well because they're both mapped to standard encodings, and Microsoft rarely implemented anything in a standard fashion. 🗡

**Comment by ConradIrwin** [comment]
It's even wrong in the microsoft help page I copied this table from: https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx

Do you have example inputs that show the difference matters in real life? The code was originally written to help with email handling, so I'd be keen to see examples of emails that purport to be in codepage 932 and which use characters that are different between windows-31j and shift-jis.

**Comment by trejkaz** [comment]
UTF-8 → Windows-31J:

    irb(main):002:0> "纊".encode(Encoding::SHIFT_JIS)
    Encoding::UndefinedConversionError: U+7E8A from UTF-8 to Shift_JIS
    	from (irb):2:in `encode'
    	from (irb):2
    	from /usr/bin/irb:12:in `<main>'
    irb(main):003:0> "纊".encode(Encoding::WINDOWS_31J)
    => "\x{FA5C}"

Windows-31J → UTF-8:

    irb(main):012:0> [250, 92].pack('C*').force_encoding(Encoding::SHIFT_JIS).encode(Encoding::UTF_8)
    Encoding::UndefinedConversionError: "\xFA\\" from Shift_JIS to UTF-8
    	from (irb):12:in `encode'
    	from (irb):12
    	from /usr/bin/irb:12:in `<main>'
    irb(main):013:0> [250, 92].pack('C*').force_encoding(Encoding::WINDOWS_31J).encode(Encoding::UTF_8)
    => "纊"

But yeah, we were trapped by the Microsoft docs being wrong multiple times in the past too. They do at least, deep in their technical docs, have a mapping file for MS932 properly documented, but the simplified information shown in normal web pages just seems to be wrong more often than it's right.

**Comment by ConradIrwin** [comment]
Makes sense, want to send a pull request?
